# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'UpsoclApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Google/SignIn'
  pod 'Fabric'
  pod 'TwitterKit'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Google/SignIn'
  pod 'GoogleAnalytics'
  pod 'Google/Analytics'

  # Pods for UpsoclApp

  target 'UpsoclAppTests' do
    inherit! :search_paths
    
    # Pods for testing
  end

end
