# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'appupsocl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '8.0'
  use_frameworks!
  pod 'Fabric'
  pod 'TwitterKit'
  pod 'Google/SignIn'
  pod 'Google/Analytics'
  pod 'Google/CloudMessaging'

  # Pods for appupsocl

end
