# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'appupsocl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Fabric'
  pod 'TwitterKit'
  pod 'Google/SignIn'
  pod 'Google/Analytics'
  pod 'Google/CloudMessaging'

  
  # Pods for appupsocl

end
